# Perry configuration file
[mongodb]
username = "test"
password = "testtest1"
hostname = ""
port = 55958
database = "gps-data"

[mqtt]
hostname = "broker.hivemq.com"
username = ""
password = ""

[panel]
port = 8080
token = "jnjrineifnajen"